/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.ui;

import javax.swing.JOptionPane;
import mx.itson.domain.Cliente;
import mx.itson.services.CarritoService;
import mx.itson.services.ClienteService;

/**
 *
 * @author gabri
 */
public class Login extends javax.swing.JFrame {

    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        String email = txtCorreo.getText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pngFerreteria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlFondoLogin = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        pnlLoginHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        pswPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pngFerreteria.setBackground(new java.awt.Color(255, 153, 51));
        pngFerreteria.setMaximumSize(new java.awt.Dimension(350, 600));
        pngFerreteria.setMinimumSize(new java.awt.Dimension(350, 600));
        pngFerreteria.setPreferredSize(new java.awt.Dimension(300, 600));
        pngFerreteria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/assets/AA.jpg"))); // NOI18N
        pngFerreteria.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 600));

        getContentPane().add(pngFerreteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        pnlFondoLogin.setBackground(new java.awt.Color(242, 242, 242));

        pnlLogin.setBackground(new java.awt.Color(250, 209, 112));

        pnlLoginHeader.setBackground(new java.awt.Color(18, 44, 50));

        jLabel2.setBackground(new java.awt.Color(131, 62, 116));
        jLabel2.setFont(new java.awt.Font("Miriam Libre", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 154, 29));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FERRETERIA");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlLoginHeaderLayout = new javax.swing.GroupLayout(pnlLoginHeader);
        pnlLoginHeader.setLayout(pnlLoginHeaderLayout);
        pnlLoginHeaderLayout.setHorizontalGroup(
            pnlLoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLoginHeaderLayout.setVerticalGroup(
            pnlLoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtCorreo.setText("Correo");

        pswPassword.setText("pass");

        jButton1.setBackground(new java.awt.Color(18, 44, 50));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 209, 112));
        jButton1.setText("Iniciar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pswPassword)
                    .addComponent(txtCorreo)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addComponent(pnlLoginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(0, 104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLoginLayout = new javax.swing.GroupLayout(pnlFondoLogin);
        pnlFondoLogin.setLayout(pnlFondoLoginLayout);
        pnlFondoLoginLayout.setHorizontalGroup(
            pnlFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLoginLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pnlFondoLoginLayout.setVerticalGroup(
            pnlFondoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLoginLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 590, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Aquí debes agregar la lógica de autenticación
                String email = txtCorreo.getText();
                String password = new String(pswPassword.getPassword());

                try {
                    // Llamar al método de autenticación
                    ClienteService clienteService = new ClienteService();
                    Cliente cliente = clienteService.autentificacion(email, password);

                    if (cliente != null) {
                        // Si se autentifica correctamente abrir las otras ventanas
                        JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso.");
                        FormProductos formP = new FormProductos();
                        formP.setEmail(email);
                        this.setVisible(false);
                        FormProductos productos = new FormProductos();
                        productos.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Inicio de sesión fallido. Verifica los datos");
                    }
                } catch (Exception ex) {
//                  throw ex;
                    JOptionPane.showMessageDialog(null, "Fallo al iniciar sesión.");
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pngFerreteria;
    private javax.swing.JPanel pnlFondoLogin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginHeader;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
